name: federated_bayes
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - astunparse=1.6.3
  - attrs=21.4.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blas=1.0
  - bleach=4.1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2021.10.8
  - certifi=2021.10.8
  - cffi=1.15.0
  - charset-normalizer=2.0.12
  - cryptography=36.0.1
  - cudatoolkit=11.1.1
  - cudatoolkit-dev=11.2.2
  - cudnn=8.2.1.32
  - cytoolz=0.11.2
  - dbus=1.13.6
  - debugpy=1.5.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.4.7
  - ffmpeg=4.3
  - flit-core=3.7.1
  - fontconfig=2.13.96
  - freetype=2.10.4
  - gettext=0.19.8.1
  - glib=2.68.4
  - glib-tools=2.68.4
  - gmp=6.2.1
  - gnutls=3.6.13
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=3.3
  - importlib-metadata=4.11.2
  - importlib_resources=5.4.0
  - intel-openmp=2021.4.0
  - ipykernel=6.9.1
  - ipython=8.1.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jedi=0.18.1
  - jinja2=3.0.3
  - jpeg=9b
  - jsonschema=4.4.0
  - jupyter=1.0.0
  - jupyter_client=7.1.2
  - jupyter_console=6.4.0
  - jupyter_core=4.9.2
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.2
  - keras-preprocessing=1.1.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libglib=2.68.4
  - libgomp=11.2.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libpng=1.6.37
  - libprotobuf=3.19.4
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtiff=4.2.0
  - libuuid=2.32.1
  - libuv=1.43.0
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libxml2=2.9.9
  - libzlib=1.2.11
  - lz4-c=1.9.3
  - markupsafe=2.1.0
  - matplotlib-inline=0.1.3
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - nbclient=0.5.12
  - nbconvert=6.4.2
  - nbformat=5.2.0
  - ncurses=6.2
  - nest-asyncio=1.5.4
  - nettle=3.6
  - ninja=1.10.2
  - notebook=6.4.8
  - numpy=1.21.2
  - numpy-base=1.21.2
  - olefile=0.46
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - packaging=21.3
  - pandas=1.4.1
  - pandoc=2.17.1.1
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=21.2.4
  - prometheus_client=0.13.1
  - prompt-toolkit=3.0.27
  - prompt_toolkit=3.0.27
  - protobuf=3.19.4
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=22.0.0
  - pyqt=5.9.2
  - pyrsistent=0.18.1
  - pysocks=1.7.1
  - python=3.9.7
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytorch=1.9.0=py3.9_cuda11.1_cudnn8.0.5_0
  - pytorch-mutex=1.0=cuda
  - pytz=2021.3
  - pyyaml=6.0
  - pyzmq=22.3.0
  - qt=5.9.7
  - qtconsole=5.2.2
  - qtconsole-base=5.2.2
  - qtpy=2.0.1
  - readline=8.1
  - requests=2.27.1
  - send2trash=1.8.0
  - setuptools=58.0.4
  - sip=4.19.13
  - six=1.16.0
  - sqlite=3.36.0
  - stack_data=0.2.0
  - termcolor=1.1.0
  - terminado=0.13.3
  - testpath=0.6.0
  - tk=8.6.11
  - torchaudio=0.9.0
  - tornado=6.1
  - traitlets=5.1.1
  - tzdata=2021a
  - urllib3=1.26.8
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.0
  - widgetsnbextension=3.5.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.7.0
  - zlib=1.2.11
  - zstd=1.4.9
  - zstd=1.4.9
  - torchvision==0.10.0=py39_cu111 
  - pip:
    - --find-links https://storage.googleapis.com/jax-releases/jax_releases.html
    - absl-py==0.13.0
    - chex==0.0.8
    - cloudpickle==2.0.0
    - cycler==0.10.0
    - decorator==5.1.0
    - dm-tree==0.1.6
    - flatbuffers==2.0
    - flax==0.3.4
    - gast==0.5.2
    - imageio==2.9.0
    - jax==0.2.20
    - jaxlib==0.1.71+cuda111
    - joblib==1.0.1
    - kiwisolver==1.3.2
    - matplotlib==3.4.3
    - msgpack==1.0.2
    - networkx==2.6.3
    - opt-einsum==3.3.0
    - optax==0.0.9
    - pillow==8.3.2
    - pyparsing==2.4.7
    - pywavelets==1.1.1
    - scikit-image==0.18.3
    - scikit-learn==0.24.2
    - scipy==1.7.1
    - tensorflow-probability==0.14.0
    - threadpoolctl==2.2.0
    - tifffile==2021.8.30
    - toolz==0.11.1
    - tqdm==4.62.2
    - typing-extensions==3.10.0.2
